### ISSUE TITLE
Plugin deprecated

### ISSUE THREAD

**Issue by HendrikWismans** [panec/postcss-mq-optimize#16]
Can this plugin update to work correctly with postcss 8?

Postcss version: 8.4.21

Warning:
```
postcss-mq-optimize: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration

```

**Comment by panec** [comment]
@HendrikWismans Please check with the latest code. I hope it should work now with version ^8.0.0
#17

**Comment by HendrikWismans** [comment]
Thanks! It works fine :)
