### ISSUE TITLE
min-width consolidations choose the largest value instead of the smallest

### ISSUE THREAD

**Issue by Bub-la-bub** [panec/postcss-mq-optimize#4]
When a media query has two min-width values this plugin currently chooses to keep the largest value and removes the smallest value.  This is a "breaking" choice since the the styles defined for the smallest min-width will be lost.

/* Input example */
@media (min-width: 200px) and (max-width: 300px) and (min-width: 100px) {
  .bar {}
}
/* Current Output example */
@media (min-width: 200px) and (max-width: 300px) {
  .bar {}
}

/* Should be */
@media (min-width: 100px) and (max-width: 300px) {
  .bar {}
}

**Comment by panec** [comment]
This is not a breaking change. Please check this code pen to test your browser https://codepen.io/panec/pen/NWpVeRv.
MQ will be matched when all of the conditions will be met, so only between 200px and 300 px viewport width styles should be applied.

**Comment by panec** [comment]
@Bub-la-bub please confirm that this is resolved so that I can close it.
